In [1]:
import numpy as np

In [12]:
arr = np.array([1,2,3]) # Create a numpy array
arr

array([1, 2, 3])

In [10]:
a = [1,2,3,4.4,"Khan"]
a

[1, 2, 3, 4.4, 'Khan']

In [13]:
np.array(a)

array(['1', '2', '3', '4.4', 'Khan'], dtype='<U32')

In [14]:
list = [[1,2,3],[4,5,6],[7,8,9]]
print(list)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
np.array(list) #converts a list in multi-direction


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr = np.zeros((6,4)) #generates zeros in multi-Array
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
arr = np.ones((5,6))
arr


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [36]:
arr = np.linspace(1,2,100)
arr

array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

Random Genration Functions

In [40]:
np.random.rand(10)

array([0.61952456, 0.60664313, 0.68405614, 0.73601477, 0.02325063,
       0.731544  , 0.24732069, 0.46406277, 0.07207479, 0.36274375])

In [44]:
np.random.randn(10)

array([-1.14304821,  0.31029759, -0.02393582, -0.94666352, -0.26028782,
        1.65908758, -2.14137152,  0.83935267,  1.2938565 , -0.10894763])

In [ ]:
np.random.randint(8) #generates only a random number not numbers

3

In [ ]:
np.random.randint(1,10,100) #Genertes 100 random numbers between 1 and 10

array([9, 3, 7, 3, 3, 5, 6, 3, 9, 2, 1, 3, 6, 4, 7, 2, 2, 7, 5, 5, 4, 6,
       2, 4, 9, 5, 9, 6, 6, 4, 6, 9, 9, 6, 9, 4, 6, 6, 9, 3, 7, 8, 6, 9,
       5, 4, 8, 5, 8, 4, 1, 5, 2, 6, 2, 4, 7, 6, 5, 8, 1, 3, 8, 9, 4, 2,
       9, 7, 6, 6, 6, 4, 1, 8, 4, 3, 4, 5, 7, 4, 8, 5, 4, 9, 8, 5, 5, 2,
       8, 8, 4, 2, 1, 2, 2, 4, 5, 4, 5, 5], dtype=int32)

Array Attributes

In [67]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arr.shape

(3, 3)

In [54]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

Array Methods

In [59]:
print(arr.min())

1


In [60]:
print(arr.max())

8


In [62]:
print(arr.sum())

42


In [ ]:
np.sum(arr, axis = 0) #Gives the columns sum

array([11, 14, 17])

In [ ]:
np.sum(arr, axis = 1) #Gives the Rows sum

array([ 6, 15, 21])

In [68]:
arr.mean()

np.float64(5.0)

In [70]:
print(arr.std())

2.581988897471611


In [ ]:
print(arr.argmax()) #return maximum element index in an Array

8


In [ ]:
print(arr.argmin()) #return minimum element index in an Array

0


In [78]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [80]:
arr.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

Numpy Indexing and Slicing of Vectors and Matrix including Boolean Indexing

In [15]:
import numpy as np
array = np.arange(1,11)
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
print(array[6])

7


In [16]:
array[0:5]

array([1, 2, 3, 4, 5])

In [17]:
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [18]:
array[1::3]

array([2, 5, 8])

In [26]:
matrix = np.arange(1,25).reshape(6,4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [32]:
matrix[2,3]

np.int64(12)

In [40]:
matrix[3:,2:]

array([[15, 16],
       [19, 20],
       [23, 24]])

In [51]:
matrix[2:4,1:3]

array([[10, 11],
       [14, 15]])

In [61]:
matrix[0:1,2:]

array([[3, 4]])

In [68]:
matrix[3:4,2:]

array([[15, 16]])

In [74]:
demo = np.arange(1,13).reshape(4,3)
print(demo)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [76]:
demo[2:,:2]

array([[ 7,  8],
       [10, 11]])

In [97]:
mat = np.arange(1,6)
print(mat)

[1 2 3 4 5]


In [98]:
boolean = mat % 2 == 0
boolean

array([False,  True, False,  True, False])

In [94]:
arr2 = mat[boolean]
print(f"This is the array {arr2} having a reminder ZERO") # f --> format
# arr2 


This is the array [32 34 36 38 40 42 44 46 48 50] having a reminder ZERO


Array operation

In [95]:
import numpy as np

In [ ]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([1,2,3,4,5])

#add = a1 + a2
#sub = a1 - a2
mul = a1 * a2
mul

div = a1 // a2
div

pow = a1 ** a2
pow




array([21, 22, 23, 24, 25])

Broadcasting

In [ ]:
a1 + 20 #Broadcasting




In [4]:
import numpy as np
m = np.arange(1,51).reshape(5,10)
m


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [10]:
save = m * 10 #Broadcasting in Matrix
save

array([[ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150, 160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250, 260, 270, 280, 290, 300],
       [310, 320, 330, 340, 350, 360, 370, 380, 390, 400],
       [410, 420, 430, 440, 450, 460, 470, 480, 490, 500]])

Deep and Shallow

In [12]:
a = np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
slice = a[:6]
slice

array([1, 2, 3, 4, 5, 6])

In [17]:
slice = slice + 20
slice 

array([41, 42, 43, 44, 45, 46])

In [ ]:
a #show the Shallow copy of an Array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
#If I store the Sliced Array into another variable then we can make the deep changes into Original Array.
a.copy() # ---> Shallow Copy
b = a

In [54]:
b[6] =  10
b

array([10,  2,  3,  4,  5,  6, 10,  8,  9, 10, 11, 12, 13, 14])

In [55]:
a # So this a Deep Copy of an Array

array([10,  2,  3,  4,  5,  6, 10,  8,  9, 10, 11, 12, 13, 14])

Matrix Operation

In [57]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [58]:
A

array([[1, 2],
       [3, 4]])

In [59]:
B

array([[5, 6],
       [7, 8]])

In [60]:
A + B

array([[ 6,  8],
       [10, 12]])

In [62]:
dot = np.dot(A,B)
dot

array([[19, 22],
       [43, 50]])

In [ ]:
A.T # Transpose of a matrix

array([[1, 3],
       [2, 4]])

In [ ]:
np.vstack((A,B)) #vertical Stacking

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.hstack((A,B)) # horizontal stack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [70]:
np.column_stack((A,B))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [78]:
d = np.arange(16).reshape(4,4)
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [79]:
np.hsplit(d,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [80]:
np.vsplit(d,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

Exercises

In [81]:
import numpy as np

Sudoku

In [94]:

s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [95]:
s.sum()

np.int64(405)

In [100]:
save = np.sum(s,axis = 1)

In [101]:
save == 45


array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [82]:
data = np.array([
    [10, 20, 40],
    [40, 56, 23],
    [12, 90, 22],
    [55, 66, 77],
    [88, 99, 11],
    ])